<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>logRancherJava</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.info.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Installer log</string>
			<key>match</key>
			<string>^(\d{4}\/\d{2}\/\d{2} \d{2}\:\d{2}\:\d{2}) \- (.*)$</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.error.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>exception jboss</string>
			<key>match</key>
			<string>^([a-zA-Z\s]*)(.*Exception\:)(\s*.*)$</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.warn.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>stacktrace jboss</string>
			<key>match</key>
			<string>^(\s*)(at )(.*)(\(.*\))$</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.warn.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.warn.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.warn.message.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>warn jboss</string>
			<key>match</key>
			<string>^(.*)( WARN | WARNING )</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.info.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.info.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.info.message.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>info jboss</string>
			<key>match</key>
			<string>^(.*)(INFO)</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.error.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.error.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.error.message.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>error jboss</string>
			<key>match</key>
			<string>^(.*)( ERROR )</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.debug.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.debug.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.debug.message.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>debug jboss</string>
			<key>match</key>
			<string>^(.*)(DEBUG)</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.trace.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.trace.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.trace.message.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>trace jboss</string>
			<key>match</key>
			<string>^(.*)(TRACE)</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>control.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.logRancherJava</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.logRancherJava</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.fatal.message.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>fatal jboss</string>
			<key>match</key>
			<string>^(.*)( FATAL )</string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.package.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.package.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Installer log</string>
			<key>match</key>
			<string> - (.*) - </string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.package.logRancherJava</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.package.logRancherJava</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Installer log</string>
			<key>match</key>
			<string>\](.[43])\: </string>
			<key>name</key>
			<string>string.quoted.logRancherJava</string>
		</dict>
		
	</array>
	<key>scopeName</key>
	<string>text.logRancherJava</string>
	<key>uuid</key>
	<string>59d2eab0-506c-4c33-8e2f-a6a74820383b</string>
</dict>
</plist>
